export enum UserErrors {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_INVALID_PASSWORD = 'USER_INVALID_PASSWORD',
  USER_INVALID_USERNAME = 'USER_INVALID_USERNAME',
  USER_INVALID_EMAIL = 'USER_INVALID_EMAIL',
  USER_INVALID_NAME = 'USER_INVALID_NAME',
}
